/*
 * Built-in MSX BIOS symbol table for the msxdebug engine.
 *
 * Unlike fujinet-go-adam-desktop's symbols_builtin.c (an exhaustive EOS/OS7
 * table machine-generated by tools/symbols/extract-symbols.py from a
 * verified source disassembly), this project has no equivalent verified
 * source to generate from. Rather than reconstruct the full MSX BIOS jump
 * table from memory and risk stating wrong addresses as fact, this is
 * deliberately a SMALL, conservative subset: the VDP/PSG/cassette/keyboard/
 * printer I/O block (WRTVDP through LPTSTT), which is internally
 * self-consistent -- every entry in this block is a 3-byte JP slot at a
 * fixed 3-byte stride from its neighbours (with the NMI vector at 0x0066
 * skipped, since that address is wired by the Z80 itself, not the BIOS
 * table), and its two ends independently anchor to the entry point names
 * most universally cited in MSX documentation -- plus the two best-known
 * interrupt hooks (H.KEYI, H.TIMI).
 *
 * These are ROM entry-point addresses, constant across every MSX/MSX2/
 * MSX2+ BIOS version and manufacturer by design (indirecting through a
 * fixed jump table is the entire point of it) -- a table of facts, not
 * program code, the same determination COMPLIANCE.md makes for the
 * upstream disassembly ADAM's own table draws from. For a fuller table
 * (the slot-access primitives RDSLT/WRSLT/CALSLT/ENASLT/CALLF, or a
 * project's own routine names), load one with msxdebug_symbols_load()
 * rather than expect it here.
 *
 * Copyright (C) 2026 Thomas Cherryhomes
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

const char msxdebug_builtin_bios_sym[] =
    "# MSX BIOS jump table (VDP/PSG/cassette/keyboard/printer I/O block)\n"
    "47 WRTVDP   ; write a VDP register\n"
    "4A RDVRM    ; read a byte from VRAM\n"
    "4D WRTVRM   ; write a byte to VRAM\n"
    "50 SETRD    ; set VDP address for a VRAM read\n"
    "53 SETWRT   ; set VDP address for a VRAM write\n"
    "56 FILVRM   ; fill a block of VRAM with a value\n"
    "59 LDIRMV   ; block move VRAM -> RAM\n"
    "5C LDIRVM   ; block move RAM -> VRAM\n"
    "5F CHGMOD   ; change screen mode\n"
    "62 CHGCLR   ; change screen colors\n"
    "69 CLRSPR   ; clear/init the sprite attribute table\n"
    "6C INITXT   ; init SCREEN 0 (text 40-col)\n"
    "6F INIT32   ; init SCREEN 1 (text 32-col)\n"
    "72 INIGRP   ; init SCREEN 2 (graphics)\n"
    "75 INIMLT   ; init SCREEN 3 (multicolor)\n"
    "78 SETTXT   ; switch to SCREEN 0 without reinitializing tables\n"
    "7B SETT32   ; switch to SCREEN 1 without reinitializing tables\n"
    "7E SETGRP   ; switch to SCREEN 2 without reinitializing tables\n"
    "81 SETMLT   ; switch to SCREEN 3 without reinitializing tables\n"
    "84 CALPAT   ; compute a sprite pattern's VRAM address\n"
    "87 CALATR   ; compute a sprite's attribute-table VRAM address\n"
    "8A GSPSIZ   ; get current sprite size\n"
    "8D GRPPRT   ; print a character in a graphics screen\n"
    "90 GICINI   ; init the PSG (AY-3-8910) and joystick ports\n"
    "93 WRTPSG   ; write a PSG register\n"
    "96 RDPSG    ; read a PSG register\n"
    "99 STMOTR   ; control the cassette motor relay\n"
    "9C CHSNS    ; check keyboard buffer for a pending key (no wait)\n"
    "9F CHGET    ; get a character from the keyboard (waits)\n"
    "A2 CHPUT    ; output a character to the screen\n"
    "A5 LPTOUT   ; output a character to the printer\n"
    "A8 LPTSTT   ; get printer status\n"
    "# Interrupt hooks (RAM, fixed page-3 addresses)\n"
    "FD9A H.KEYI ; keyboard-scan interrupt hook\n"
    "FD9F H.TIMI ; vertical-retrace (50/60Hz) interrupt hook\n";
